### ISSUE TITLE
v3 doesn't work

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#21]
Here is my package.json:
```json
{
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "devDependencies": {
    "vite": "^2.0.5",
    "vite-plugin-solid": "^1.3.0",
    "vite-imagetools": "^3.0.1"
  },
  "dependencies": {
    "sass": "^1.32.8",
    "solid-app-router": "^0.0.34",
    "solid-js": "^0.24.13",
    "solid-meta": "^0.24.13",
    "solid-styled-components": "^0.24.13"
  }
}
```

I import an image like this:
```typescript
import { width } from "./images/main.jpg?webp";
```

I'm getting this error in console:
```
Uncaught (in promise) SyntaxError: The requested module '/data/portfolio/work-01/images/main.jpg?import&webp' does not provide an export named 'width'
```

**Comment by YamiteruXYZ** [comment]
An this is my vite.config.ts:

```typescript
import { defineConfig } from "vite";
import solidPlugin from "vite-plugin-solid";
import { imagetools } from "vite-imagetools";


export default defineConfig({
  plugins: [
    imagetools(),
    solidPlugin()
  ],
  build: {
    target: "esnext",
    polyfillDynamicImport: false,
  },
});
```

**Comment by JonasKruckenberg** [comment]
```js
import Image from 'example.jpg?webp&meta'
```

Should work. You need the `meta` directive to tell vite-imagetools that you want to import it as an object

**Comment by JonasKruckenberg** [comment]
Or add `metadata` both directives work

**Comment by YamiteruXYZ** [comment]
It doesn't work in development using `vite`. In the network tab it shows 404 not found + it's trying to load the original image.

**Comment by YamiteruXYZ** [comment]
Also when I import an image like this:
```typescript
import image from "./images/main.jpg?width=200;400&meta";
```

It shows this error when I want to build the project:
![image](https://user-images.githubusercontent.com/34185465/110796192-f9499400-8277-11eb-859a-2ffd7ff7d454.png)

**Comment by JonasKruckenberg** [comment]
Yep I missed that issue sorry 🤦‍♂️ anyway, did a push against main just now, risky but should work now 👍

**Comment by JonasKruckenberg** [comment]
Can you confirm wether the problem is gone in the latest version published to npm?

**Comment by YamiteruXYZ** [comment]
Yes the issue regarding sizes works 👍
