### ISSUE TITLE
Support import.meta.glob

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#24]
It'd be awesome if we could leverage glob import to for example import all images in a directory AND apply transformations on all of them.

I image it'd be used just like this:
```typescript
const images = import.meta.glob("./images/*.jpg?width=200;400&format=webp;jpg&meta");
```

The exported object might look like this:
```typescript
{
  "./images/01.jpg": {
    "width=200&format=webp&meta": () => Promise<metadata>,
    "width=200&format=jpg&meta": () => Promise<metadata>,
    "width=400&format=webp&meta": () => Promise<metadata>,
    "width=400&format=jpg&meta": () => Promise<metadata>
  }
}
```

If we use `globEager` instead of `glob` we would get the `metadata` object instead of `() => Promise<metadata>`.

**Comment by JonasKruckenberg** [comment]
I'll try to see if this is possible once #17 is properly working, at least on `next`.
I don't know how Vite behaves when glob importing so I can make no promises but I definitely doesn't seem complicated

**Comment by JonasKruckenberg** [comment]
Alright, I've been digging around a bit in the vitejs source code and it seems that they are passing the full url to fast-glob, so importing your example `./images/*.jpg?width=200;400&format=webp;jpg&meta` Vite will try to match files in the asset directory with the pattern `*.jpg?width=200;400&format=webp;jpg&meta` which will obviously not match anything.

So it seems like for now glob imports don't work no. :/

**Comment by YamiteruXYZ** [comment]
Thanks for investigating the issue. 

That sucks.. because in several occasions dynamic `import(`${url}.jpg?webp`)` could not be resolved which means I have to import every image manually meaning having for example 10 image import statements at the beginning of one file.

**Comment by JonasKruckenberg** [comment]
Yeah that's very annoying yeah.
Can you share a situation in which the glob import doesn't resolve? 
Maybe we can work around that somehow!
Maybe it'd be worth it to raise it as an issue over at the vite repo. I'll try to to this tomorrow if I have the time 👍🏻

**Comment by YamiteruXYZ** [comment]
I've already deleted my prototype using dynamic imports. Tomorrow I'll try to put together repo with imports that don't resolve so we can eventually raise it as an issue at Vite.

**Comment by palle-k** [comment]
@JonasKruckenberg I had a look at the Vite source code and found that when using the `as` parameter in the import options, this should theoretically be forwarded to the import statement, e.g.:

```typescript jsx
const images = import.meta.globEager("./*.jpg", {as: "w=250"});
```

[Link to Vite source](https://github.com/vitejs/vite/blob/60721ac53a1bf326d1cac097f23642faede234ff/packages/vite/src/node/plugins/importMetaGlob.ts#L401)

However, this does not seem to work in practice, transforms are not applied.

**Comment by benmccann** [comment]
@palle-k I think you'd want to use `query` for that: https://vitejs.dev/guide/features.html#custom-queries

**Comment by alphacornutum** [comment]
This I find is also a very good template: https://github.com/sveltejs/kit/issues/241#issuecomment-1363621896

**Comment by benmccann** [comment]
I've added `import.meta.glob` to the docs and example to show how to use it
