### ISSUE TITLE
Support development mode

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#25]
I import image like this:
```typescript
import imageUrl from "./01.jpg?webp";
```

I run the app in dev mode via `vite`.

When I log the `imageUrl` I see:
```
/Users/yamiteru/dev/yamiteru.xyz/data/portfolio/12345sestak/01.jpg
```

instead of something like this:
```
/assets/01.c74cd79a.webp
```

Having full functionality in dev mode is crucial since building and serving takes too much time for creating fast iterations of design/development. Moreover the absolute path returned in the current version in dev mode doesn't even load the original image.

**Comment by JonasKruckenberg** [comment]
Have you tried setting the plugins force option to true?
I have transforms in devmode deactivated by default currently since it's a terrible hack😄.
But maybe I'll come up with a better solution 🤔

**Comment by YamiteruXYZ** [comment]
Ooh I see. That fixed it! Thanks ❤️
