### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#3]
I really love the idea of this plugin and I'm planning on heavily using it in production. I have a few feature requests:

1. **Image metadata**
```typescript
import { width, height, src } from "./image.jpg?format=webp&width=1000";
```

Thanks to this we could create rectangles with exact aspect ratio of the images so the page wouldn't jump as the images load. This would be extremely useful.

2. **Plugin settings**
```typescript
{
  input: ["jpg", "jpeg"],
  output: ["jpg", "webp"],
  quality: 80,
  sizes: [500, 1000, 2000, 4000],
  include: "./images"
}
``` 

This would take a folder from `include`, look for images from `input` and generate different `sizes` in different formats from `output` in a given `quality`. This is useful when image loading is dynamic (eg. dependant on user device resolution and format support).

I know this could be achieved by a library like gulp or webpack, but it would be nice to have it all in one vite plugin.

**Comment by JonasKruckenberg** [comment]
I really like your first idea, it makes the return really extensible, I'll have a look how I can integrate it with version 3 👍 

The second idea however wouldn't play nice with other directives and the way those can get combined. What I'm planning for version 3 however is to make it really easy to create and import custom directives, those directives can also be higher order functions that call other directives.
So your second idea could be written as custom directive.
I will keep your use case in mind when designing the final api however, so use cases like a custom secret directive should definitely be possible.

**Comment by YamiteruXYZ** [comment]
That's really great to hear! I'm looking forward to version 3.

**Comment by JonasKruckenberg** [comment]
Version 3 has just been released! 🎉 

> 1. **Image metadata**
> 
> ```ts
> import { width, height, src } from "./image.jpg?format=webp&width=1000";
> ```

This has been addressed and you can now import all image metadata with the directive 
```js
import { width, height, src, channels } from 'example.jpg?metadata'
// or the shorthand
import { width, height, src, channels } from 'example.jpg?meta'
```



> 1. Plugin settings

When you import and image
```js
import Image from 'example.jpg?w=300&h=700&format=webp'
```
It will get translated into an options object like this
```js
{
  width: 300,
  height: 700,
  format: 'web'
}
```
I'm planning on adding a feature that'd address your point, that'd simply merge a "default" options object with the one specified by the import directives, but that'll happen in an 3.x release

**Comment by YamiteruXYZ** [comment]
You're a champ! I'm gonna try it out today and let you know how it goes 👌
