### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by YamiteruXYZ** [JonasKruckenberg/vite-imagetools#6]
As far as I can tell the v3 will become the best image compression plugin for vite. So I'd like to support this plugin via donation. I think nowadays the best place for that is https://opencollective.com.

**Comment by JonasKruckenberg** [comment]
Hey mate, thanks so much! 
To be honest I was a bit surprised by because I'd never thought someone would actually sponsor me, but that awesome!
I set up sponsorship through GitHub, with open collective in the making.
But again thanks so much for even considering this! 🙏

**Comment by YamiteruXYZ** [comment]
I'll wait till the open collective is set up since I use it for donating to all the projects I like. I hope other people will find this plugin useful and will donate as well. After I finish my project which heavily uses this plugin I'll definitely shout this plugin out.

Until then I'll probably be submitting issues and maybe later on when the first version of v3 is out I might contribute to the code as well if needed.

**Comment by JonasKruckenberg** [comment]
Yes that sounds awesome! I'm definitely looking forwards to seeing what you end up building too!
Maybe we could even have a featured projects section or something 🤔

In the meantime, I'm currently working on improved documentation, so if you stumble upon anything that's not quite clear or straight up wrong don't hesitate to open an issue! 
It's always hard to spot those issues as the one who built the thing 😅
